/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author oscar
 */
public class VistaSubasta extends javax.swing.JFrame {
    
    Calendar fecha_actual = new GregorianCalendar();
    /**
     * Creates new form Login
     */
    public VistaSubasta() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Administrar Usuarios");
        this.jdaHoraInicio.setCalendar(fecha_actual);
        this.jdaHoraFinal.setCalendar(fecha_actual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbRoles1 = new javax.swing.JComboBox<>();
        jbtAgregarUsuario1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jdaHoraFinal = new com.toedter.calendar.JDateChooser();
        jdaHoraInicio = new com.toedter.calendar.JDateChooser();
        jtxPrecioBase = new javax.swing.JTextField();
        jtxDetalleEntrega = new javax.swing.JTextField();
        jtxItem = new javax.swing.JTextField();
        jcbSubCategoria = new javax.swing.JComboBox<>();
        jcbCategoria = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistaDeTelefonos = new javax.swing.JList<>();
        jbtEliminarSubasta = new javax.swing.JButton();
        jbtAgregarSubasta = new javax.swing.JButton();
        jlaFondo = new javax.swing.JLabel();

        jcbRoles1.setBackground(new java.awt.Color(0, 0, 51));
        jcbRoles1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbRoles1.setForeground(new java.awt.Color(255, 255, 255));
        jcbRoles1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "Trabajo", "Casa", "Otros" }));

        jbtAgregarUsuario1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtAgregarUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jbtAgregarUsuario1.setText("Agregar Usuario");
        jbtAgregarUsuario1.setContentAreaFilled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/subasta.png")));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administar Subasta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Base");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Detalles de Entrega");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora Inicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subcategoria");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora Final");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Categoria");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Item");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jdaHoraFinal.setBackground(new java.awt.Color(0, 0, 51));
        jdaHoraFinal.setForeground(new java.awt.Color(255, 255, 255));
        jdaHoraFinal.setDateFormatString("dd-MMM-yyyy HH:mm:ss");
        getContentPane().add(jdaHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 260, 30));

        jdaHoraInicio.setBackground(new java.awt.Color(0, 0, 51));
        jdaHoraInicio.setForeground(new java.awt.Color(255, 255, 255));
        jdaHoraInicio.setDateFormatString("dd-MMM-yyyy HH:mm:ss");
        getContentPane().add(jdaHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 260, 30));

        jtxPrecioBase.setBackground(new java.awt.Color(0, 0, 51));
        jtxPrecioBase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxPrecioBase.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtxPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 260, -1));

        jtxDetalleEntrega.setBackground(new java.awt.Color(0, 0, 51));
        jtxDetalleEntrega.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxDetalleEntrega.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtxDetalleEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 260, -1));

        jtxItem.setBackground(new java.awt.Color(0, 0, 51));
        jtxItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxItem.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtxItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 260, -1));

        jcbSubCategoria.setBackground(new java.awt.Color(0, 0, 51));
        jcbSubCategoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbSubCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jcbSubCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Celular", "Trabajo", "Casa", "Otros" }));
        getContentPane().add(jcbSubCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, -1));

        jcbCategoria.setBackground(new java.awt.Color(0, 0, 51));
        jcbCategoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Celular", "Trabajo", "Casa", "Otros" }));
        getContentPane().add(jcbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 260, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 51));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jlistaDeTelefonos.setBackground(new java.awt.Color(0, 0, 51));
        jlistaDeTelefonos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlistaDeTelefonos.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jlistaDeTelefonos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 340, 290));

        jbtEliminarSubasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtEliminarSubasta.setForeground(new java.awt.Color(255, 255, 255));
        jbtEliminarSubasta.setText("Eliminar");
        jbtEliminarSubasta.setContentAreaFilled(false);
        getContentPane().add(jbtEliminarSubasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jbtAgregarSubasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtAgregarSubasta.setForeground(new java.awt.Color(255, 255, 255));
        jbtAgregarSubasta.setText("Agregar");
        jbtAgregarSubasta.setContentAreaFilled(false);
        getContentPane().add(jbtAgregarSubasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jlaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jlaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSubasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSubasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSubasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSubasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSubasta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtAgregarSubasta;
    public javax.swing.JButton jbtAgregarUsuario1;
    public javax.swing.JButton jbtEliminarSubasta;
    public javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbRoles1;
    public javax.swing.JComboBox<String> jcbSubCategoria;
    public com.toedter.calendar.JDateChooser jdaHoraFinal;
    public com.toedter.calendar.JDateChooser jdaHoraInicio;
    private javax.swing.JLabel jlaFondo;
    public javax.swing.JList<String> jlistaDeTelefonos;
    public javax.swing.JTextField jtxDetalleEntrega;
    public javax.swing.JTextField jtxItem;
    public javax.swing.JTextField jtxPrecioBase;
    // End of variables declaration//GEN-END:variables
}
